# Run 'docker-compose up' to create all the services

version: '3'

# Create a network named "emailnet-660046669" with IP range 192.168.1.0/24
networks:
  emailnet-660046669:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24

services:

# Start the Bluebook with static IP 192.168.1.3
  bluebook:
    build: BlueBook/.
    ports:
      - "3008:8888"
    networks:
      emailnet-660046669:
        ipv4_address: 192.168.1.3

# All the MSAs and MTAs have a "depends_on" to the Bluebook, not because the
# containers actually need the Bluebook to run, but rather because we need the
# Bluebook to have a specific static IP (192.168.1.3), so we use depends_on
# to force all the other containers to wait until Bluebook has started to
# fetch another random IP in the range 192.168.1.0/24

# Start the MSAs in any order, they will get an IP assigned to them
  msa-billgates:
    build: MSA/.
    ports:
      - "3000:8888"
    command: "billgates@here.com"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook

  msa-alanturing:
    build: MSA/.
    ports:
      - "3001:8888"
    command: "alanturing@here.com"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook

  msa-stevejobs:
    build: MSA/.
    ports:
      - "3002:8888"
    command: "stevejobs@there.com"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook

  msa-adalovelace:
    build: MSA/.
    ports:
      - "3003:8888"
    command: "adalovelace@there.com"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook

  msa-gracehopper:
    build: MSA/.
    ports:
      - "3004:8888"
    command: "gracehopper@other.org"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook

# Start the MTAs in any order, they will get an IP assigned to them
  mta-here:
    build: MTA/.
    ports:
      - "3005:8888"
    command: "here.com"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook

  mta-there:
    build: MTA/.
    ports:
      - "3006:8888"
    command: "there.com"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook

  mta-other:
    build: MTA/.
    ports:
      - "3007:8888"
    command: "other.org"
    networks:
      - emailnet-660046669
    depends_on:
      - bluebook
